
service: mysql-api-serverless 

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1

functions:
  # storeRedisDataToMaria:
  #     handler: functions/storeRedisDataToMaria.storeRedisDataToMaria
  #     events:
  #       - http:
  #           path: db/redisData
  #           method: get
  #           cors: true
  #     vpc:
  #       securityGroupIds:
  #         - sg-46415228
  #       subnetIds:
  #         - subnet-9bcc27f1
  getAllRedisData:
      handler: functions/getAllRedisData.getAllRedisData
      events:
        - http:
            path: db/getAllRedisData
            method: get
            cors: true
      vpc:
        securityGroupIds:
          - sg-46415228
        subnetIds:
          - subnet-9bcc27f1
  getRedisData:
      handler: functions/getRedisData.getRedisData
      events:
        - http:
            path: db/redisData/{id}
            method: get
            cors: true
      vpc:
        securityGroupIds:
          - sg-46415228
        subnetIds:
          - subnet-9bcc27f1
  saveToRedis:
    handler: functions/saveToRedis.saveToRedis
    events:
      - http:
          path: db/redis
          method: post
          cors: true
    vpc:
      securityGroupIds:
        - sg-46415228
      subnetIds:
        - subnet-9bcc27f1
  getAll:
    handler: functions/getAll.getAll
    events:
      - http:
          path: db
          method: get
          cors: true
  getOne:
      handler: functions/getOne.getOne
      events: 
        - http:
            path: db/{id}
            method: get
            cors: true
  create:
    handler: functions/create.create
    events: 
      - http:
          path: db
          method: post
          cors: true
  deleteOne:
    handler: functions/deleteOne.deleteOne
    events: 
      - http:
          path: db/{id}
          method: delete
          cors: true
  deleteAll:
    handler: functions/deleteAll.deleteAll
    events: 
      - http:
          path: db
          method: delete
          cors: true